<?php
use Magento\Customer\Block\Widget\Name;
use Test\Task\Model\Config\Hobby as ConfigHobby;

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php $hobby = $block->getLayout()->createBlock(\Test\Task\Block\Widget\Hobby::class) ?>
<?php if ($block->getHelperConfig()->isEnabled() && $hobby->isEnabled()): ?>
<form class="form form-edit-account"
      action="<?= $block->escapeUrl($block->getUrl('hobby/manage/save')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <?= $hobby->setHobby($block->getCustomer()->getCustomAttribute(ConfigHobby::HOBBY_ATTRIBUTE))->toHtml() ?>
        <?php endif ?>
    </fieldset>
    <div class="actions-toolbar" style="clear: left;">
        <div class="primary">
            <button id="hobby-submit-button" type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script>
    require([
        'jquery',
        'Magento_Customer/js/customer-data'
    ], function ($, customerData) {
        'use strict';
        customerData.getInitCustomerData().done(function () {
            // Reload customer data in local storage after update if any (HOBBY SAVE ACTION TARGET PAGE)
            customerData.reload(['customer'], false);
        });
    });
</script>

